version: '3.8'

services:
  app:
    container_name: springboot-app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root123
    networks:
      - springboot-network

  db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - springboot-network

volumes:
  postgres_data:

networks:
  springboot-network:
    driver: bridge
